/*
 * This file was generated by the Gradle 'init' task.
 *
 * This is a general purpose Gradle build.
 * Learn more about Gradle by exploring our samples at https://docs.gradle.org/7.3.3/samples
 */

plugins {
    kotlin("jvm") version "1.6.10"
    // https://projectlombok.org/setup/gradle
    id("io.freefair.lombok") version "6.3.0"
}

tasks.withType<org.jetbrains.kotlin.gradle.tasks.KotlinCompile> {
    kotlinOptions {
        jvmTarget = "16"
    }
}

repositories {
    mavenCentral()
}

sourceSets {
    test {
        java {
            srcDirs("src")
        }
    }
}

dependencies {
    // https://www.baeldung.com/java-testing-system-out-println
    testImplementation("com.github.stefanbirkner:system-lambda:1.2.1")
    // https://www.baeldung.com/junit-5-gradle
    testImplementation(platform("org.junit:junit-bom:5.8.2"))
    testImplementation("org.junit.jupiter:junit-jupiter")
}

tasks.test {
    useJUnitPlatform()
}
